Stat svc
v01cecrack/java-explore-with-me pull request #3
Opened 2023-09-10 23:56 UTC by v01cecrack

2023-09-13 18:45 UTC, NikolaiDem requested changes

2023-09-13 20:48 UTC, v01cecrack commented on docker-compose.yml
> +      - POSTGRES_USER=postgres
Не понял какие именно

2023-09-13 20:53 UTC, v01cecrack commented on stats-service/service/src/main/resources/schema.sql
> +CREATE TABLE stats (
Как то сложно, надеюсь можно оставить так.

2023-09-14 12:54 UTC, NikolaiDem approved these changes

2023-09-14 12:54 UTC, NikolaiDem commented on docker-compose.yml
> +      - POSTGRES_USER=postgres
POSTGRES_USER и POSTGRES_PASSWORD
Они задают переменные среды в контейнере.
А сервис статистики использует переменные 
spring.datasource.username=postgres (SPRING_DATASOURCE_USERNAME)
spring.datasource.password=iamroot (SPRING_DATASOURCE_PASSWORD)

То есть можно в контейнере поменять POSTGRES_USER  и POSTGRES_PASSWORD, но они ни на что не повлияют, так как используются SPRING_DATASOURCE_USERNAME и SPRING_DATASOURCE_PASSWORD

2023-09-14 12:54 UTC, NikolaiDem commented on stats-service/service/src/main/resources/schema.sql
> +CREATE TABLE stats (
Пример, пусть есть такие записи в таблице stats:
(1, 'music', "/1', '111.111')
(2, 'music', "/1', '111.111')
(3, 'music', "/1', '111.111')
(4, 'music', "/1', '111.111')
......
и таких еще 1 000 000 

Пусть название приложения меняется с music на "winter music"
Тогда нужно поменять > 1 000 000 строк в таблице.

А если у нас будет отдельная таблица apps(id, name)
(99, 'music', "/1', '111.111'))

А в stats будет
(1, 99, "/1', '111.111') (99 - внешний ключ на apps.id)
тогда изменить нужно одну строку в apps

2023-09-14 13:43 UTC, merged