Main_svc
v01cecrack/java-explore-with-me pull request #5
Opened 2023-09-22 22:31 UTC by v01cecrack

2023-09-23 22:01 UTC, NikolaiDem requested changes

2023-09-23 22:01 UTC, NikolaiDem commented on .github/workflows/api-tests.yml
> -on:
Читерством по удалению проверок не пользуемся

2023-09-26 18:12 UTC, v01cecrack commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImpl.java
> +                event.setConfirmedRequests(requestRepository.countAllByEventIdAndStatus(event.getId(),
не получается

2023-09-27 17:27 UTC, NikolaiDem commented on main-service/src/main/java/ru/practicum/mainservice/categories/controller/PublicCategoriesController.java
> +public class PublicCategoriesController {
На уровне класса нужно указать @Validated. Неверно написал @Valid

2023-09-27 17:28 UTC, NikolaiDem commented on main-service/src/main/java/ru/practicum/mainservice/categories/dto/CategoryDto.java
> +@Data
В проекте все еще остались сочетания Builder и Data

2023-09-27 17:30 UTC, NikolaiDem commented on main-service/src/main/java/ru/practicum/mainservice/categories/service/CategoriesServiceImpl.java
> +        log.info("Запрос GET на получение списка категорий");
Логирование такого вида осталось в RequestServiceImpl и UserServiceImpl

2023-09-27 18:36 UTC, NikolaiDem requested changes

2023-09-27 18:36 UTC, NikolaiDem commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImpl.java
> +            statisticClient.saveHit("/events/" + event.getId(), ip);
Для чего сохраняется статистика по каждому event-у здесь и для всех event-ов в строке 81?

2023-09-27 18:36 UTC, NikolaiDem commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImpl.java
> +                event.setConfirmedRequests(requestRepository.countAllByEventIdAndStatus(event.getId(),
Какой был вариант решения?

2023-09-28 00:39 UTC, v01cecrack commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImpl.java
> +                event.setConfirmedRequests(requestRepository.countAllByEventIdAndStatus(event.getId(),
создать список ивентов и сделать запрос к бд с этим списком, который вытянет список всех подтвержденных заявок, потом добавить циклом эти данные к дтошкам. Проблема именно в написании такого sql запроса.

2023-09-28 22:25 UTC, NikolaiDem approved these changes

2023-09-28 22:25 UTC, NikolaiDem commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImpl.java
> -        for (EventShortDto event : result) {
Решение просто удалить код вместо решения вопроса N+1 запроса простое, но неверное ...

2023-09-28 22:30 UTC, v01cecrack commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImpl.java
> -        for (EventShortDto event : result) {
а, я не заметил, случайно удалил

2023-09-28 22:39 UTC, merged